steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-west1-docker.pkg.dev/tienda-microservicios-456723/images-registry/auth-ms',
        '-f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/tienda-microservicios-456723/images-registry/auth-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY